version: 2

jobs:
  check:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m # Customize the JVM maximum heap limit

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "67:aa:9d:07:87:33:95:47:89:20:6b:0f:ec:2d:e3:7a"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn"}}

      - run:
          name: Generate version
          command: clojure -A:dev -m gen-version
            
      - run:
          name: Running unit tests
          command: clojure -A:test

      - run:
          name: Tag and push
          command: clojure -A:dev -m tag-and-push-version

      - save_cache:
          paths:
            - ~/.m2
            - ~/.cognitect-s3-libs
          key: v1-dependencies-{{ checksum "deps.edn"}}

workflows:
  version: 2
  main-workflow:
    jobs:
      - check
